// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/Request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPOJO_Operation int32

const (
	RequestPOJO_RETAIN           RequestPOJO_Operation = 0
	RequestPOJO_LOGOUT           RequestPOJO_Operation = 1
	RequestPOJO_JOIN_CHA         RequestPOJO_Operation = 2
	RequestPOJO_QUIT_CHA         RequestPOJO_Operation = 3
	RequestPOJO_CREATE_CHA       RequestPOJO_Operation = 4
	RequestPOJO_SENDMSG          RequestPOJO_Operation = 5
	RequestPOJO_GETMSG           RequestPOJO_Operation = 6
	RequestPOJO_HEARTBEAT        RequestPOJO_Operation = 7
	RequestPOJO_VERSION          RequestPOJO_Operation = 8
	RequestPOJO_GET_CHANNEL_LIST RequestPOJO_Operation = 9
	RequestPOJO_GET_MEMBER_LIST  RequestPOJO_Operation = 10
)

// Enum value maps for RequestPOJO_Operation.
var (
	RequestPOJO_Operation_name = map[int32]string{
		0:  "RETAIN",
		1:  "LOGOUT",
		2:  "JOIN_CHA",
		3:  "QUIT_CHA",
		4:  "CREATE_CHA",
		5:  "SENDMSG",
		6:  "GETMSG",
		7:  "HEARTBEAT",
		8:  "VERSION",
		9:  "GET_CHANNEL_LIST",
		10: "GET_MEMBER_LIST",
	}
	RequestPOJO_Operation_value = map[string]int32{
		"RETAIN":           0,
		"LOGOUT":           1,
		"JOIN_CHA":         2,
		"QUIT_CHA":         3,
		"CREATE_CHA":       4,
		"SENDMSG":          5,
		"GETMSG":           6,
		"HEARTBEAT":        7,
		"VERSION":          8,
		"GET_CHANNEL_LIST": 9,
		"GET_MEMBER_LIST":  10,
	}
)

func (x RequestPOJO_Operation) Enum() *RequestPOJO_Operation {
	p := new(RequestPOJO_Operation)
	*p = x
	return p
}

func (x RequestPOJO_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestPOJO_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Request_proto_enumTypes[0].Descriptor()
}

func (RequestPOJO_Operation) Type() protoreflect.EnumType {
	return &file_proto_Request_proto_enumTypes[0]
}

func (x RequestPOJO_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestPOJO_Operation.Descriptor instead.
func (RequestPOJO_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_Request_proto_rawDescGZIP(), []int{0, 0}
}

type RequestPOJO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation RequestPOJO_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=cn.csuosa.pojo.request.RequestPOJO_Operation" json:"operation,omitempty"`
	Message   *RequestMessage       `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Channel   *Channel              `protobuf:"bytes,3,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
}

func (x *RequestPOJO) Reset() {
	*x = RequestPOJO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPOJO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPOJO) ProtoMessage() {}

func (x *RequestPOJO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPOJO.ProtoReflect.Descriptor instead.
func (*RequestPOJO) Descriptor() ([]byte, []int) {
	return file_proto_Request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestPOJO) GetOperation() RequestPOJO_Operation {
	if x != nil {
		return x.Operation
	}
	return RequestPOJO_RETAIN
}

func (x *RequestPOJO) GetMessage() *RequestMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RequestPOJO) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel string  `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Ticket  *string `protobuf:"bytes,2,opt,name=ticket,proto3,oneof" json:"ticket,omitempty"`
	Nick    *string `protobuf:"bytes,3,opt,name=nick,proto3,oneof" json:"nick,omitempty"`
}

func (x *Channel) Reset() {
	*x = Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_proto_Request_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Channel) GetTicket() string {
	if x != nil && x.Ticket != nil {
		return *x.Ticket
	}
	return ""
}

func (x *Channel) GetNick() string {
	if x != nil && x.Nick != nil {
		return *x.Nick
	}
	return ""
}

type RequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_Request_proto_rawDescGZIP(), []int{2}
}

func (x *RequestMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RequestMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_Request_proto protoreflect.FileDescriptor

var file_proto_Request_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6e, 0x2e, 0x63, 0x73, 0x75, 0x6f, 0x73, 0x61,
	0x2e, 0x70, 0x6f, 0x6a, 0x6f, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xab, 0x03,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x4f, 0x4a, 0x4f, 0x12, 0x4b, 0x0a,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2d, 0x2e, 0x63, 0x6e, 0x2e, 0x63, 0x73, 0x75, 0x6f, 0x73, 0x61, 0x2e, 0x70, 0x6f, 0x6a,
	0x6f, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x4f, 0x4a, 0x4f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6e,
	0x2e, 0x63, 0x73, 0x75, 0x6f, 0x73, 0x61, 0x2e, 0x70, 0x6f, 0x6a, 0x6f, 0x2e, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x3e, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6e, 0x2e, 0x63, 0x73, 0x75, 0x6f, 0x73, 0x61, 0x2e, 0x70,
	0x6f, 0x6a, 0x6f, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x48, 0x01, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x88, 0x01,
	0x01, 0x22, 0xaf, 0x01, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0a, 0x0a, 0x06, 0x52, 0x45, 0x54, 0x41, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c,
	0x4f, 0x47, 0x4f, 0x55, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x4f, 0x49, 0x4e, 0x5f,
	0x43, 0x48, 0x41, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x51, 0x55, 0x49, 0x54, 0x5f, 0x43, 0x48,
	0x41, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48,
	0x41, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x4e, 0x44, 0x4d, 0x53, 0x47, 0x10, 0x05,
	0x12, 0x0a, 0x0a, 0x06, 0x47, 0x45, 0x54, 0x4d, 0x53, 0x47, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09,
	0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x56,
	0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x08, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x45, 0x54, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x09, 0x12, 0x13,
	0x0a, 0x0f, 0x47, 0x45, 0x54, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x53,
	0x54, 0x10, 0x0a, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x6d, 0x0a, 0x07, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x1b, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e,
	0x69, 0x63, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x22, 0x44, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x42, 0x2d, 0x0a, 0x18, 0x63, 0x6e, 0x2e, 0x63, 0x73, 0x75, 0x6f, 0x73, 0x61, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x01, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Request_proto_rawDescOnce sync.Once
	file_proto_Request_proto_rawDescData = file_proto_Request_proto_rawDesc
)

func file_proto_Request_proto_rawDescGZIP() []byte {
	file_proto_Request_proto_rawDescOnce.Do(func() {
		file_proto_Request_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Request_proto_rawDescData)
	})
	return file_proto_Request_proto_rawDescData
}

var file_proto_Request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_Request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_Request_proto_goTypes = []interface{}{
	(RequestPOJO_Operation)(0), // 0: cn.csuosa.pojo.request.RequestPOJO.Operation
	(*RequestPOJO)(nil),        // 1: cn.csuosa.pojo.request.RequestPOJO
	(*Channel)(nil),            // 2: cn.csuosa.pojo.request.Channel
	(*RequestMessage)(nil),     // 3: cn.csuosa.pojo.request.RequestMessage
}
var file_proto_Request_proto_depIdxs = []int32{
	0, // 0: cn.csuosa.pojo.request.RequestPOJO.operation:type_name -> cn.csuosa.pojo.request.RequestPOJO.Operation
	3, // 1: cn.csuosa.pojo.request.RequestPOJO.message:type_name -> cn.csuosa.pojo.request.RequestMessage
	2, // 2: cn.csuosa.pojo.request.RequestPOJO.channel:type_name -> cn.csuosa.pojo.request.Channel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_Request_proto_init() }
func file_proto_Request_proto_init() {
	if File_proto_Request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPOJO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_Request_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_Request_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_Request_proto_goTypes,
		DependencyIndexes: file_proto_Request_proto_depIdxs,
		EnumInfos:         file_proto_Request_proto_enumTypes,
		MessageInfos:      file_proto_Request_proto_msgTypes,
	}.Build()
	File_proto_Request_proto = out.File
	file_proto_Request_proto_rawDesc = nil
	file_proto_Request_proto_goTypes = nil
	file_proto_Request_proto_depIdxs = nil
}
